name: 'Setup go'
description: 'Setup Go with job based cache naming strategy'
inputs:
  go-version-file:
    description: 'Path to go.mod file'
    required: false
    default: 'go.mod'
  cache-dependency-path:
    description: 'Path to cache dependency file e.g. go.sum'
    required: false
    default: 'go.sum'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  job-name:
    description: 'Job name for cache key'
    required: false
    default: ${{ github.job }}
outputs:
  go-version:
    description: 'Go version that was installed'
    value: ${{ steps.setup-go.outputs.go-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache-go.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: 'actions/setup-go@v5'
      working-directory: ${{ inputs.working-directory }}
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache: false
    - name: Cache
      uses: 'actions/cache@v4'
      working-directory: ${{ inputs.working-directory }}
      env:
        go-version: ${{ steps.setup-go.outputs.go-version }}
        job-name: ${{ inputs.job-name }}
        go-sum-hash: ${{ hashFiles(**/go.sum) }}
        date: ${{ date }}
      with:
        path: |
          '~/.cache/go-build'
          '~/go/pkg/mod'
        key: golang-${{ runner.os }}-${{ env.go-version }}-${{ env.job-name }}-${{ env.go-sum-hash }}-${{ env.date }}
        restore-keys: |
          golang-${{ runner.os }}-${{ env.go-version }}-${{ env.job-name }}-${{ env.go-sum-hash }}-${{ env.date }}
          golang-${{ runner.os }}-${{ env.go-version }}-${{ env.job-name }}-${{ env.go-sum-hash }}
          golang-${{ runner.os }}-${{ env.go-version }}-${{ env.job-name }}
          golang-${{ runner.os }}-${{ env.go-version }}
          golang-${{ runner.os }}